from pathlib import Path
from datetime import datetime


REPORTS_DIR = Path("reports")


def generate_report(case_data):
    REPORTS_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    report_path = REPORTS_DIR / f"report_{timestamp}.md"

    content = f"""# Blacklistr Investigation Report

## Summary

**Target:** {case_data['target']}

**Type:** {case_data['type']}

**Risk Score:** {case_data['score']}/100

**Severity:** {case_data['severity']}

---

## Findings

"""

    if case_data["reasons"]:
        for reason in case_data["reasons"]:
            content += f"- {reason}\n"
    else:
        content += "- No obvious indicators detected\n"

    content += "\n---\nGenerated by Blacklistr\n"

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(content)

    return report_path
